### PR TITLE
Need help on Scroll/Layout - Completed NightMode

### PR DESCRIPTION
**Pull request by Mclblack**

### CODE REVIEW

**Comment by j-ulienguyen** [comment]
@Mclblack I've resolved the conflicts for you to continue working. But I am not sure if you would need to update your branch again with the changes.

**Comment by j-ulienguyen** [comment]
@Mclblack Keep in mind that your comp is much bigger in comparison to Header and Footer, so you may need to adjust the value of flex accordingly to a higher value.

I would suggest creating a new View + Text tags and style them with flex, place it above Story and below, and visually see it.

**Comment by j-ulienguyen** [comment]
> @Mclblack Keep in mind that your comp is much bigger in comparison to Header and Footer, so you may need to adjust the value of flex accordingly to a higher value.
> 
> I would suggest creating a new View + Text tags and style them with flex, place it above Story and below, and visually see it.

The extra view tags would just act as a placeholder for Header and Footer incase you dont have it

**Comment by j-ulienguyen** [comment]
> I'm struggling with the layout and ScrollView. Doing research to figure out ScollView now but could use help.

Ill checkout to your branch to see what it looks like in the sim

**Comment by Mclblack** [comment]
> > I'm struggling with the layout and ScrollView. Doing research to figure out ScollView now but could use help.
> 
> Ill checkout to your branch to see what it looks like in the sim

Okay are you going to work on my branch? Should I check out to avoid conflicts?

**Comment by j-ulienguyen** [comment]
> > > I'm struggling with the layout and ScrollView. Doing research to figure out ScollView now but could use help.
> > 
> > 
> > Ill checkout to your branch to see what it looks like in the sim
> 
> Okay are you going to work on my branch? Should I check out to avoid conflicts?

No I won't edit your files so you can keep working on it. Ill give you a few pointers though

**Comment by Mclblack** [comment]
> > > > I'm struggling with the layout and ScrollView. Doing research to figure out ScollView now but could use help.
> > > 
> > > 
> > > Ill checkout to your branch to see what it looks like in the sim
> > 
> > 
> > Okay are you going to work on my branch? Should I check out to avoid conflicts?
> 
> No I won't edit your files so you can keep working on it. Ill give you a few pointers though

Great thanks

**Comment by j-ulienguyen** [comment]
You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.

And from there you can have 2 containers that sit on top of each other in a flex column view.

**Comment by Mclblack** [comment]
> You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> 
> And from there you can have 2 containers that sit on top of each other in a flex column view.

I think I've already done that. I will push my latests edits

**Comment by Mclblack** [comment]
> > You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> > And from there you can have 2 containers that sit on top of each other in a flex column view.
> 
> I pushed my latest edits

**Comment by Mclblack** [comment]
> > > You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> > > And from there you can have 2 containers that sit on top of each other in a flex column view.
> > 
> > 
> > I pushed my latest edits

Any suggestions? I'm totally stuck

**Comment by Mclblack** [comment]
> > > > You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> > > > And from there you can have 2 containers that sit on top of each other in a flex column view.
> > > 
> > > 
> > > I pushed my latest edits
> 
> Any suggestions? I'm totally stuck

Want to checkout to my branch and give it a try? I can help Elias

**Comment by j-ulienguyen** [comment]
> > > > > You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> > > > > And from there you can have 2 containers that sit on top of each other in a flex column view.
> > > > 
> > > > 
> > > > I pushed my latest edits
> > 
> > 
> > Any suggestions? I'm totally stuck
> 
> Want to checkout to my branch and give it a try? I can help Elias

Sure I will try to do that. I'm just finishing up my component

**Comment by Mclblack** [comment]
> > > > > > You would need to start nesting your Switches in a new View tag so that it is contained separately from the Lorem Ipsum portion. These switches would have a flex row view so that they sit side by side.
> > > > > > And from there you can have 2 containers that sit on top of each other in a flex column view.
> > > > > 
> > > > > 
> > > > > I pushed my latest edits
> > > 
> > > 
> > > Any suggestions? I'm totally stuck
> > 
> > 
> > Want to checkout to my branch and give it a try? I can help Elias
> 
> Sure I will try to do that. I'm just finishing up my component

Cool, let me know how it goes

**Comment by j-ulienguyen** [comment]
I got the interface to change accordingly to the theme mode switch! will continue working on it

**Comment by Mclblack** [comment]
> I got the interface to change accordingly to the theme mode switch! will continue working on it

Good job lead developer

**Comment by Mclblack** [comment]
> I got the interface to change accordingly to the theme mode switch! will continue working on it



> > I got the interface to change accordingly to the theme mode switch! will continue working on it
> 
> Good job lead developer

Should we merge this?

**Pull request merged**
