### PR TITLE
header level 2 help!

### PR DESCRIPTION
**Pull request by eliastayag**
quick help:
I need to change the <Text> to the value of the <TextInput>, right now i set the value to go as an alert so it works but i just need it to change the <Text> instead of making an alert.

### CODE REVIEW

**Comment by eliastayag** [comment]
*typo*
I need to change the to the value of the <Text> to match what the input says, right now i set the input value to go as an alert so it works but i just need it to change the instead of making an alert

**Comment by Mclblack** [comment]
> quick help:
> I need to change the to the value of the , right now i set the value to go as an alert so it works but i just need it to change the instead of making an alert.

Okay I will help just trying to figure it out

**Comment by eliastayag** [comment]
Still no luck with mine, i think we should merge what we have so far to see everything put put together

**Comment by j-ulienguyen** [comment]
> Still no luck with mine, i think we should merge what we have so far to see everything put put together

Sure, lets do that and see how it is. Afterwards we can create a new branch to fix the changes for the Header

**Pull request merged**
